version: '3'
services:
  app:
    build: .
    environment:
      MYSQL_HOST: db
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: db_example
      MYSQL_USER: springuser
      MYSQL_PASSWORD: ThePassword
      MYSQL_ROOT_PASSWORD: TheRootPassword
    volumes:
      - ./db_data:/var/lib/mysql
